volumes:
  asmr-db-data-dev:
  asmr-db-data-staging:
  asmr-db-data-prod:
  asmr-db-data:
  
networks:
  asmrchive:
    driver: bridge

services:

  redis:
    image: docker.io/library/redis:7.2.4
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - asmrchive
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    build: ./Postgres
    image: ${DB_IMAGE_NAME}
    container_name: ${DB_CONTAINER_NAME}
    networks:
      - asmrchive
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DB_VOLUME_NAME}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 2
  
  django:
    depends_on:
      - redis
      - db
    build: ./Django
    image: ${DJANGO_IMAGE_NAME}
    container_name: ${DJANGO_CONTAINER_NAME}
    volumes:
      - ./Django:/app
    ports:
      - ${DJANGO_PORT}:8000
    networks:
      - asmrchive
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_CONTAINER_NAME: ${DB_CONTAINER_NAME}
      DB_PORT: ${DB_PORT}
