services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - asmr-db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  asmr-db-data: