name: Version Bump

on:
  push:
    branches:
      - dev-1
    paths-ignore:
      - '**/*.md'

jobs:
  check-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for Skip
        id: check_skip
        run: |
          echo "Checking for [skip ci] in the commit message"
          SKIP_CI=$(git log -1 --pretty=%B | grep -c "\[skip ci\]" || true)
          echo "::set-output name=skip::$SKIP_CI"
          if [ "$SKIP_CI" -ne "0" ]; then
            echo "[skip ci] found"
          else
            echo "[skip ci] not found"
          fi
  bump-version:
    needs: check-skip
    runs-on: ubuntu-latest
    if: needs.check-skip.outputs.skip == '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary for commit history inspection

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the Python version

      - name: Install semver
        run: pip install semver

      - name: Run Version Bump Script
        run: ./bump_version.sh

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt CHANGELOG.md
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push
