name: Version Bump

on:
  push:
    branches:
      - dev-1
    paths-ignore:
      - "*.md"
      - "version.txt"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check for skip
        run: export skip=$(git log -n 1 | grep "[skip-ci]" | wc -l)

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the Python version

      - name: Install semver
        run: python -m pip install semver

      - name: Run Version Bump Script
        run: ./bump_version.sh

      - name: Commit and Push Changes
        run: |
          git config --local user.email "whgdomi@gmail.com"
          git config --local user.name "GitHub Action"
          git add version.txt CHANGELOG.md
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push
