name: Version Bump

on:
  push:
    branches:
      - dev-1
    paths-ignore:
      - "*.md"
      - "./version.txt"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check for skip
        run: |
          skip_count=$(git log -n 1 | grep "\[skip-ci\]" | wc -l)
          if [ $skip_count -ge 1 ]; then
            skip=1
          else
            skip=0
          fi
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the Python version

      - name: Install semver
        run: python -m pip install semver

      - name: Run Version Bump Script
        run: |
          skip_count=$(git log -n 1 | grep "\[skip-ci\]" | wc -l)
          if [ $skip_count -ge 1 ]; then
            echo Skipping CI as commit contains [skip-ci]
          else
            ./bump_version.sh
            git config --local user.email "whgdomi@gmail.com"
            git config --local user.name "GitHub Action"
            git add version.txt CHANGELOG.md
            git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
            git push
          fi